name: Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: npm test

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "logs/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          threshold_metric: "lines"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on the pull request
        uses: peter-evans/pull-request-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for creating this pull request! We appreciate your contribution. 
            We will review it shortly. 😊
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
