name: Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: npm i

      - name: Test
        run: npm run test

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage/